name: flutter_firebase_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  intl: ^0.19.0
  image_picker: ^1.1.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.7
  file_picker: ^8.0.5
  fluttertoast: ^8.2.6
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.3.0
  connectivity_plus: ^4.0.2
  email_validator: ^3.0.0
  youtube_player_flutter: ^9.0.3
  audioplayers: ^6.1.0
  animate_do: ^3.3.4
  curved_navigation_bar: ^1.0.3
  syncfusion_flutter_gauges: ^20.3.58
  percent_indicator: ^4.2.3
  dashed_circular_progress_bar: ^0.0.6
  flutter_svg: ^1.0.3
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Modules/Module0/
    - assets/icons/
    - assets/audio/1.4Module1Podcast.wav

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto/Roboto-BoldItalic.ttf
        
